### ISSUE TITLE
Lexer（単語分割）

### ISSUE THREAD

**Issue by ism-ismis** [ism-ismis/minishell#1]
https://nafuka.hatenablog.com/entry/2021/03/29/194200

Lexerでは入力文字列を構文解析しやすいよう、単語に分割します。

**状態の更新**
入力文字列を先頭から1文字ずつ見ていって、状態を更新していきます。

状態は以下の3つのいずれかです。

**通常**
シングルクォートの中
ダブルクォートの中
今見ている文字が ' なら状態をシングルクォートの中に、 " なら状態をダブルクォートの中に更新します。
対応するクォートが現れたら、状態を通常に戻します。

**単語分割**
状態が通常の時にスペース、 ; | > など、単語を分割すべき文字を見つけたら、そこで単語を分割します。

Lexerの段階では、まだ " ' は残ったままです。" ' は 3. Expansion で除去します。

**Comment by yksdyy** [comment]
done!
